import os
from google import genai
from google.genai import types

from dotenv import load_dotenv

from attunement.config import GEMENI_MODEL_NAME

# It's good practice to load environment variables once at the module level
load_dotenv()


grounding_tool = types.Tool(
    google_search=types.GoogleSearch()
)

config = types.GenerateContentConfig(
    tools=[grounding_tool]
)

# Define the retry options using the types.HttpRetryOptions
retry_options = types.HttpRetryOptions(
    attempts=5,          # Maximum total attempts (original + 4 retries)
    exp_base=7,          # Delay multiplier (controls exponential backoff)
    initial_delay=1,     # Initial delay in seconds
    # The SDK handles retrying on standard server errors (5xx) and 429
    # but you can explicitly specify or modify the list if needed.
    # http_status_codes=[429, 500, 503, 504], # Included by default in most Google clients
)

# Bundle the retry options into the HttpOptions for the client
http_options = types.HttpOptions(
    retry_options=retry_options,
    timeout=120_000, # e.g., 120 seconds in milliseconds
)



def get_text_from_gemini(prompt_string, model_name=GEMENI_MODEL_NAME): 
    """
    Calls the Gemini model with the provided prompt string and returns the generated text.
    
    Args:
        prompt_string (str): The fully formatted prompt to send to the model.
        
    Returns:
        str: The essay text generated by the model, or an error message.
    """    
    
    # NOTE: You must ensure 'GEMINI_API_KEY' and 'client' are available in your environment or passed to this function.
    text_client = genai.Client(api_key = os.getenv("GEMINI_API_KEY"), http_options=http_options)
    
    try:
        response = text_client.models.generate_content(
            model=model_name,
            contents=prompt_string,
            config=config, 
        )
        # Ensure the response is successfully parsed
        return str(response.text) 
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise Exception
    
    