from openai import OpenAI
from dotenv import dotenv_values
from dotenv import load_dotenv

from attunement.config import OPENROUTER_MODEL_NAME

# It's good practice to load environment variables once at the module level
load_dotenv()

config = dotenv_values(".env")


def get_text_from_openrouter(prompt_string, model_name=OPENROUTER_MODEL_NAME): 

    """
    Calls the OpenRouter model with the provided prompt string and returns the generated text.
    
    Args:
        prompt_string (str): The fully formatted prompt to send to the model.
        
    Returns:
        str: The essay text generated by the model, or an error message.
    """   

    client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key= config["OPENROUTER_API_KEY"],
    )

    try:
        response = client.responses.create(
            model=model_name,
            input=prompt_string
        )
        return response.output_text
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise Exception



 
    
    